### ISSUE TITLE
msf files

### ISSUE THREAD

**Issue by jshackatpair** [JackDinn/tbtray#10]
I'm trying to set up folders that are not INBOX.msf to be checked, and some of these folders have spaces in the names. Is there a syntax for this that tbtray will accept and use?

**Comment by JackDinn** [comment]
Its been a while since i looked at the code but you should be able to just put the path into the "profile path selector" input box and then add it to the main list.

I added a test file with a space in the name. The name does not have to be INBOX.msf i dont think but i think it needs the .msf sufix though :-
![ZZ_20200414-200538](https://user-images.githubusercontent.com/5557560/79263779-5cc21a80-7e8b-11ea-9c98-627190b1400f.png)

**Comment by jshackatpair** [comment]
Thanks for the quick reply.
I did get tbtray to accept a couple of entries with spaces in them, but it doesn't appear to be actually checking those folders. The INBOX.msf one works perfectly, but an otherwise identical line with /otherwise/identical/path/to/files/Support Team.msf doesn't.

**Comment by JackDinn** [comment]
Hmm, i would have to take a good look, refresh my memory how it all worked etc. 

I have a odd feeling that i specifically left it just reading INBOX.msf files because there was a problem with the syntax of anything other and i had a job parsing them plus as i was not intending to use anything other than my own INBOX.msf files i didn't spent to much time scratching my head.
 
I shall take a quick look tomorrow though.

**Comment by JackDinn** [comment]
I have taken a look and unfortunately i was remembering correctly there is a problem with parsing anything other than INBOX.msf files. It would need a rather large re-write to implement a proper thunderbird .msf parser.

Sorry i cant offer a better answer.
