### ISSUE TITLE
Thunderbird 68 support?

### ISSUE THREAD

**Issue by geckolinux** [JackDinn/tbtray#5]
Hi there,

tbtray 1.7 doesn't seem to be able to show new message counts with Thunderbird 68.  Can anybody confirm or deny this? Thanks!

**Comment by JackDinn** [comment]
working for me with TB Version : 68.1.1 
The problem might be that sometimes the INBOX.msf files get corrupted. 
Try deleting the INBOX.msf file that TBtray is pointing at and restarting thunderbird & tbtray. It will re-build the INBOX.msf. If you are using multiple INBOX's then it's likely to be just one of them causing the problem but its hard to know exactly which one so you might need to re-built them all one at a time.

i.e. in the example from the README the file to delete would be :-
/home/user/.thunderbird/tzvg3gbn.default/ImapMail/imap.gmail.com/INBOX.msf

You might want to rename it instead of deleting it, just for safety's sake. You can delete it after its been re-built if all goes well.

**Comment by geckolinux** [comment]
https://github.com/JackDinn/tbtray/issues/8#issuecomment-543995306
